config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/login', to: 'admin/sessions#new'
  post 'admin/login', to: 'admin/sessions#create'
  delete 'admin/logout', to: 'admin/sessions#destroy'
  namespace :admin do
    resources :products
    resources :categories
    resources :users
    resources :sessions, only: %i[new create destroy]
  end
  get 'myfood/signup', to: 'users#new'
  post 'myfood/signup', to: 'users#create'
  get 'myfood/login', to: 'sessions#new'  
  post 'myfood/login', to: 'sessions#create'  
  delete 'myfood/logout', to: 'sessions#destroy'
  get 'users/new'
  resources :users, only: [:new, :create, :update, :edit, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  root 'myfood#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/myfood_controller.rb
# frozen_string_literal: true

class MyfoodController < ApplicationController
    def edit
        @user = User.find(params[:id])
    end
end

app/helpers/myfood_helper.rb
# frozen_string_literal: true

module MyfoodHelper
end

app/views/myfood/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
  <html>
    <head>
      <title><%= yield(:title) %> | My Food Page </title>
  </head>
<body>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
    </aside>
  </div>
  <section class= 'user_info'>
    <%= render 'shared/user_info' %>
  </section>
<% else %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<h2>
  <%= link_to  "My Food Page", root_path %> 
</h2>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Log in", myfood_login_url, method: :get %>
        <%= link_to "Sign up", myfood_signup_url, method: :get %>
      </li>
    </ul>
  </div>
</nav>
</body>
<% end %>