config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/login', to: 'admin/sessions#new'
  post 'admin/login', to: 'admin/sessions#create'
  delete 'admin/logout', to: 'admin/sessions#destroy'
  namespace :admin do
    resources :products
    resources :categories
    resources :users
    resources :sessions, only: %i[new create destroy]
  end
  get 'myfood/signup', to: 'users#new'
  post 'myfood/signup', to: 'users#create'
  get 'myfood/login', to: 'sessions#new'  
  post 'myfood/login', to: 'sessions#create'  
  delete 'myfood/logout', to: 'sessions#destroy'
  get 'users/new'
  resources :users, only: [:new, :create, :update, :edit, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  root 'myfood#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name_category, presence: true
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: %i[edit update]
  def index
    @categories = Category.all.page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = 'Add successfully'
      redirect_to admin_categories_path
    else
      flash[:danger] = 'Add fails'
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = 'Update successfully'
      redirect_to admin_categories_path
    else
      flash[:danger] = 'Update fails'
      render :edit
    end
  end

  def destroy
    @category = Category.find_by id: params[:id]
    @category.destroy
    redirect_to request.referrer || root_url
  end

  private

  def category_params
    params.require(:category).permit :name_category
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<tr>
	<td><%= index + 1 %></td>
	<td><%= category.name_category %></td>
	<td>	
    <%= link_to edit_admin_category_path(category) do %>
		  <i class='fas fa-edit' style='font-size:24px; color: black'></i>
    <% end %>
		<%= link_to admin_category_path(category), method: :delete do %>
			<i class='far fa-trash-alt' style='font-size:24px; color: black'></i>
		<% end %>
	</td>
</tr>

app/views/admin/categories/edit.html.erb
<h3>Update Category</h3>
<div class="container">
  <%= form_for [:admin, @category] do |f|%>
    <%= render 'shared/error_messages', object: @category%>
    <div class="create-category">
        <%= f.text_field :name_category, placeholder:"Add category" %>
    </div>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
    <h2>CATEGORIES</h2>
    <%=link_to "Create new caregory", new_admin_category_path, class: "btn btn-origin"%>
    <%= form_tag admin_categories_path, :method => 'get', :class => "form-inline" do %>
      <div>
        <%= text_field_tag :search, params[:search], class:'form-control mr-sm-2',placeholder: 'Looking for category' %>
        <%= submit_tag "Search", :name => nil, class: 'btn btn-origin' %>
      </div>
    <% end %>
	<table id="products">
		 <tr>
		 	<th>ID</th>
		 	<th>Name</th>
		 	<th>Action</th>
		 </tr>
		<% @categories.each_with_index do |category, index| %>
      <%= render 'category', category: category, index: index %>
		<% end %>
	</table>
	<%= paginate @categories, theme: 'twitter-bootstrap-4' %>	
</div>

app/views/admin/categories/new.html.erb
<%= render 'shared/form_create_category' %>