config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/login', to: 'admin/sessions#new'
  post 'admin/login', to: 'admin/sessions#create'
  delete 'admin/logout', to: 'admin/sessions#destroy'
  namespace :admin do
    resources :products
    resources :categories
    resources :users
    resources :sessions, only: %i[new create destroy]
  end
  get 'myfood/signup', to: 'users#new'
  post 'myfood/signup', to: 'users#create'
  get 'myfood/login', to: 'sessions#new'  
  post 'myfood/login', to: 'sessions#create'  
  delete 'myfood/logout', to: 'sessions#destroy'
  get 'users/new'
  resources :users, only: [:new, :create, :update, :edit, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  root 'myfood#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :images
  has_many :product_carts
  belongs_to :category
  validates :name_product, presence: true, length: { maximum: 50 }
  validates :price, presence: true, numericality: true
  validates :information, presence: true, length: { maximum: 255 }
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < Admin::BaseController
  before_action :get_product, only: %i[show edit update]
  before_action :logged_in?, only: %i[index new create update destroy]
  def index
    @products = Product.all.page(params[:page]).per(5)
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = 'create successful product'
      redirect_to admin_products_path
    else
      flash[:alert] = 'Product could not be created!'
      render :new
    end
  end

  def edit; end

  def update
    if @product.update product_params
      flash[:success] = 'Update Successfuly'
      redirect_to admin_categories_path
    else
      flash[:alert] = 'Product could not be Update'
      render :edit
    end
  end

  def destroy
    @product = Product.find_by id: params[:id]
    @product.destroy
    redirect_to admin_categories_path
  end

  private

  def product_params
    params.require(:product).permit :name_product, :information, :price, :type, :category_id
  end

  def get_product
    @product = Product.find(params[:id])
  end

  def logged_in? # Returns true if the user is logged in
    !current_admin.nil?
  end
end

app/helpers/admin/products_helper.rb
# frozen_string_literal: true

module Admin::ProductsHelper
  def product_types
    [
      ['Do uong', 'Drink'],
      ['Do an', 'Food']
    ]
  end
end

app/views/admin/products/_product.html.erb
<tr>
	<td><%= product.name_product%></td>
	<td><%= product.information%></td>
	<td>$<%= product.price%> </td>
	<td><%= product.type%></td>
	<td><%=product.category.name_category%> </td>
	<td>
		<%= link_to edit_admin_product_path(product) do %>
		  <i class='fas fa-edit' style='font-size:24px; color: black'></i>
    <% end %>
		<%= link_to admin_product_path(product), method: :delete do%>
			<i class='far fa-trash-alt' style='font-size:24px; color: black'></i>
		<% end %>
	</td>
</tr>

app/views/admin/products/edit.html.erb
<h3>UPDATE PRODUCT</h3>
<div class="container">
    <%= form_for :product , url:admin_product_path(@product), method: :patch do |f| %>
        <%= render 'shared/error_messages', object: @product %>
        <div class="field">
            <%= f.text_field :name_product , placeholder:"Enter name product" %>
        </div>
        <div class="text">
            <%= f.text_area :information ,  placeholder:"Enter desciption"%>
        </div>
        <div class="field">
            <%= f.text_field :price , placeholder:"Enter price product"%>
        </div>
        <div class="field">
            <%= f.select :type, product_types %>
        </div>
        <div class="caregory">
            <%= f.select :category_id, Category.all.collect {|u| [u.name_category, u.id]}, :prompt => 'Select' %>
        </div>
        
        <%= f.submit "Update product", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/admin/products/index.html.erb
<div class="container">
	<h2>List Products</h2>
	<%=link_to "Create new product", new_admin_product_path, class: "btn btn-origin" %>
	   <%= form_tag @product, url: admin_products_path, :method => 'get', :class => "form-inline" do %>
      <div>
        <%= text_field_tag :search, params[:search], class:'form-control mr-sm-2',placeholder: 'Looking for products' %>
        <%= submit_tag "Search", :name => nil, class: 'btn btn-origin' %>
      </div>
    <% end %>
	<table id="products">
		<tr>
			<th>NAME PRODUCT</th>
			<th>INFORMATION</th>
			<th>PRICE</th>
			<th>TYPE</th>
			<th>CATEGORY</th>
			<th>ACTION</th>
		</tr>
		<% @products.each do |product|%>
			<%= render 'product' , product: product%>
		<% end %>
	</table>
	<%= paginate @products, theme: 'twitter-bootstrap-4' %>	
</div>

app/views/admin/products/new.html.erb
<%= render "shared/form_create_product" %>

app/views/admin/products/show.html.erb
<div class="container">
	<div class="row">
		<aside class="col-md-4">
			<section class="info-product"> 
				<h2>
					<%= @product.name_product%>
				</h2>
			</section>
		</aside>
		<aside class="col-md-8">
			<section class="product-details">
				<h4 class="desciption">DESCRIPTION</h4>
					<span class="text"> <%= @product.information%></span>
				<h4 class="price">PRICE</h4>
					<span class="$"><%= @product.price %> $</span>
				<h4 class="type">TYPE</h4>
					<span class="kind"> <%= @product.type%></span>
			</section>
		</aside>
	</div>
</div>