config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/login', to: 'admin/sessions#new'
  post 'admin/login', to: 'admin/sessions#create'
  delete 'admin/logout', to: 'admin/sessions#destroy'
  namespace :admin do
    resources :products
    resources :categories
    resources :users
    resources :sessions, only: %i[new create destroy]
  end
  get 'myfood/signup', to: 'users#new'
  post 'myfood/signup', to: 'users#create'
  get 'myfood/login', to: 'sessions#new'  
  post 'myfood/login', to: 'sessions#create'  
  delete 'myfood/logout', to: 'sessions#destroy'
  get 'users/new'
  resources :users, only: [:new, :create, :update, :edit, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  root 'myfood#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header_admin.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
        <nav class="navbar navbar-expand-sm">
          <%= link_to admin_categories_path, class:"navbar-brand" do %>
            <i class='fas fa-hamburger' style='font-size:48px;color:#ff8e02cf'></i>
          <% end %>
          <% if logged_in? %>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to  "Home", admin_categories_path, class:"nav-link active" %>
              </li>
              <li class="nav-item dropdown">
                <%= link_to "Dashboard","#", class:"nav-link dropbtn"%>
                <div class="dropdown-content">
                  <%= link_to admin_categories_path do%>
                    <i class='far fa-file-alt' style="color: #e65805cf;"></i>Category
                  <% end %>
                   <%= link_to admin_products_path do%>
                    <i class='fas fa-hotdog' style="color: #e65805cf;"></i>Product
                  <% end %>
                </div>
              </li>
            </ul>
          </nav>
        </div>
        <div class="col-md-3">
          <div class="notification">
            <div class="dropdown">
              <%= link_to "#", class:"dropbtn" do %>
                <i class='fas fa-user-circle' style='font-size:24px;color:#ff8e02cf'></i>
              <% end %>
              <div class="dropdown-content">
                <%= link_to "Profile","#"%>
                <%= link_to "Setting","#" %>
                <%= link_to "Log out",logout_path, method: :delete%>
                <% else %>
                <%= link_to "Login",admin_login_path %>
                <% end %>  
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_header_user.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My Food Page",root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if logged_in? %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Profile", current_user, class: "dropdown-item" %>
                <%= link_to "Update your Profile", edit_user_url(current_user),class: "dropdown-item" %>
                <%= link_to "Log out", myfood_logout_path, method: :delete,class: "dropdown-item" %>
              </div>
            </div>
          <% else %>
            <%= link_to "Log in", myfood_login_url, method: :get %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Food </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,300&display=swap" rel="stylesheet">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if  admin_logged_in? %>
      <%= render 'layouts/header_admin' %>
    <%  elsif logged_in? %>
      <%= render 'layouts/header_user' %>
    <% end %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %><div class="container">
      <%= yield %>
    </div>
  </body>
</html>